In [1]:
import pandas as pd
import glob

from processing import processing_pipeline, no_processing, processing

In [4]:
fps = [
    "./glucose_flour_mixes/0/*.csv", 
    "./glucose_flour_mixes/15/*.csv", 
    "./glucose_flour_mixes/25/*.csv",
    "./glucose_flour_mixes/35/*.csv", 
    "./glucose_flour_mixes/45/*.csv", 
    "./glucose_flour_mixes/50/*.csv",
    "./glucose_flour_mixes/75/*.csv", 
    "./glucose_flour_mixes/100/*.csv"
    ] # Path to folders for each height

labels = [0, 0.15, 0.25, 0.35, 0.45, 0.5, 0.75, 0.85, 1] # Labels for each height/group

In [5]:
data = processing_pipeline(fps, labels)
cols_to_drop = [col for col in data.columns if col <= 4500]
data = data.drop(columns=cols_to_drop)
data

Processing ./glucose_flour_mixes/0/*.csv with label 0...
Processing ./glucose_flour_mixes/15/*.csv with label 0.15...
Processing ./glucose_flour_mixes/25/*.csv with label 0.25...
Processing ./glucose_flour_mixes/35/*.csv with label 0.35...
Processing ./glucose_flour_mixes/45/*.csv with label 0.45...
Processing ./glucose_flour_mixes/50/*.csv with label 0.5...
Processing ./glucose_flour_mixes/75/*.csv with label 0.75...
Processing ./glucose_flour_mixes/100/*.csv with label 0.85...

Wavenumber,4501.041,4504.898,4508.755,4512.612,4516.469,4520.326,4524.183,4528.040,4531.896,4535.754,...,9966.316,9970.173,9974.030,9977.887,9981.744,9985.601,9989.458,9993.314,9997.172,10001.030
0.00,0.368909,0.371250,0.365693,0.365159,0.360829,0.357576,0.355040,0.356554,0.354889,0.347379,...,0.184542,0.178153,0.177718,0.180572,0.173209,0.168235,0.171978,0.176712,0.172280,0.168966
0.00,0.174039,0.171243,0.155967,0.157244,0.160958,0.160517,0.163248,0.159695,0.159699,0.164543,...,0.148533,0.146436,0.142626,0.145708,0.151303,0.145216,0.132038,0.135004,0.136618,0.140038
0.00,0.136935,0.121657,0.128571,0.139961,0.128281,0.116669,0.125559,0.130501,0.128288,0.118640,...,0.061725,0.052813,0.050689,0.058184,0.062055,0.062467,0.065904,0.058885,0.050026,0.049251
0.00,0.406242,0.400763,0.402500,0.402956,0.405200,0.405639,0.394606,0.392809,0.388402,0.392009,...,0.068231,0.065292,0.067868,0.072777,0.068126,0.062028,0.065154,0.067731,0.067351,0.065652
0.00,0.362856,0.353994,0.346843,0.346984,0.347116,0.345381,0.343901,0.345708,0.334150,0.325251,...,0.142166,0.144459,0.144330,0.146200,0.151574,0.146458,0.141956,0.135055,0.132481,0.141057
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0.85,0.555258,0.556772,0.560092,0.556223,0.554091,0.554223,0.552431,0.560476,0.564071,0.570377,...,0.062581,0.061989,0.061168,0.060477,0.058960,0.063098,0.066309,0.062699,0.063096,0.061129
0.85,0.586003,0.593413,0.589558,0.598289,0.603600,0.606577,0.610223,0.606317,0.603439,0.606896,...,0.123145,0.124818,0.124524,0.126314,0.127380,0.129594,0.127124,0.126583,0.124586,0.125121
0.85,0.579945,0.592876,0.584950,0.580428,0.582088,0.575230,0.575615,0.583541,0.583483,0.592932,...,0.080313,0.077472,0.077117,0.078712,0.079774,0.082540,0.079884,0.077831,0.076295,0.074526
0.85,0.570594,0.573988,0.576377,0.572245,0.578236,0.583994,0.586108,0.586958,0.589191,0.591778,...,0.045519,0.042929,0.042077,0.044491,0.044328,0.043269,0.042787,0.042323,0.040255,0.040373
0.85,0.560474,0.554475,0.554789,0.558621,0.564401,0.570781,0.578055,0.568319,0.572939,0.576329,...,0.071323,0.067944,0.067224,0.065638,0.066325,0.070320,0.072691,0.070655,0.065343,0.063607

In [7]:
mean_data= pd.DataFrame(columns=data.columns)
for ind in set(data.index.to_list()):
    mean_data.loc[ind] = data.loc[ind].mean()

mean_data

Wavenumber,4501.041,4504.898,4508.755,4512.612,4516.469,4520.326,4524.183,4528.040,4531.896,4535.754,...,9966.316,9970.173,9974.030,9977.887,9981.744,9985.601,9989.458,9993.314,9997.172,10001.030
0.00,0.313222,0.310504,0.308032,0.307492,0.303451,0.302590,0.304279,0.304118,0.300165,0.299960,...,0.121401,0.116257,0.114833,0.119916,0.122568,0.119960,0.120457,0.116264,0.111652,0.115936
0.25,0.343154,0.340116,0.337950,0.338454,0.339203,0.340524,0.344123,0.344531,0.339683,0.337599,...,0.115835,0.109763,0.108253,0.114550,0.117682,0.116073,0.115611,0.110467,0.105247,0.109710
0.35,0.402148,0.401193,0.399617,0.400266,0.400320,0.399867,0.401974,0.402284,0.400504,0.400120,...,0.117305,0.112452,0.108848,0.112613,0.115293,0.115467,0.115562,0.110026,0.104907,0.108773
0.45,0.468923,0.468001,0.467227,0.470509,0.469688,0.468512,0.468480,0.467838,0.467067,0.466522,...,0.112364,0.107805,0.105111,0.109446,0.113000,0.111050,0.110521,0.105946,0.102681,0.104785
0.15,0.339258,0.337350,0.334899,0.334199,0.335760,0.337098,0.338231,0.335806,0.329840,0.328924,...,0.096008,0.091209,0.089521,0.094605,0.097086,0.096470,0.096328,0.091130,0.086503,0.090365
0.50,0.433179,0.433906,0.435851,0.436736,0.435835,0.434398,0.431161,0.429973,0.428087,0.430127,...,0.108336,0.103521,0.100687,0.104485,0.107581,0.106659,0.106103,0.101001,0.097021,0.101547
0.75,0.489546,0.488634,0.491058,0.493446,0.491222,0.493183,0.494617,0.495026,0.492518,0.492351,...,0.076295,0.072328,0.069850,0.073708,0.076843,0.074592,0.073723,0.069870,0.066843,0.069524
0.85,0.563271,0.566439,0.567105,0.568281,0.570012,0.572528,0.576241,0.575026,0.576080,0.578816,...,0.087897,0.087926,0.087646,0.088642,0.089092,0.089671,0.089720,0.089040,0.087880,0.087304