In [22]:
import pandas as pd
import glob

from processing import processing_pipeline, no_processing, processing

In [23]:
fps = [
    "../glucose_flour_mixes/0/*.csv", 
    "../glucose_flour_mixes/15/*.csv", 
    "../glucose_flour_mixes/25/*.csv",
    "../glucose_flour_mixes/35/*.csv", 
    "../glucose_flour_mixes/45/*.csv", 
    "../glucose_flour_mixes/50/*.csv",
    "../glucose_flour_mixes/55/*.csv",
    "../glucose_flour_mixes/65/*.csv",
    "../glucose_flour_mixes/75/*.csv", 
    "../glucose_flour_mixes/100/*.csv"
    ] 

foods_fps = [
    "../foods/buttermilk_biscuit/*.csv",
    "../foods/inst_potatoes/*.csv",
    "../foods/mixed_gravy/*.csv",
    "../foods/nonfat_milk/*.csv",
    "../foods/parmesan/*.csv",
    "../foods/parmesan_romano/*.csv",
    "../foods/protein_pancake/*.csv",
    "../foods/tapioca/*.csv",
    ]


labels = [0, 0.15, 0.25, 0.35, 0.45, 0.5, 0.55, 0.65, 0.75, 1] 
food_labels = ["buttermilk_biscuit", "inst_potatoes", "mixed_gravy", "nonfat_milk", "parmesan", "parmesan_romano", "protein_pancake", "tapioca"]

In [24]:
data = processing_pipeline(fps, labels)
cols_to_drop = [col for col in data.columns if col <= 4500]
data = data.drop(columns=cols_to_drop)

data.to_csv("processed_flour_sugar_data.csv", index=True)
data

Processing ../glucose_flour_mixes/0/*.csv with label 0...
Processing ../glucose_flour_mixes/15/*.csv with label 0.15...
Processing ../glucose_flour_mixes/25/*.csv with label 0.25...
Processing ../glucose_flour_mixes/35/*.csv with label 0.35...
Processing ../glucose_flour_mixes/45/*.csv with label 0.45...
Processing ../glucose_flour_mixes/50/*.csv with label 0.5...
Processing ../glucose_flour_mixes/55/*.csv with label 0.55...
Processing ../glucose_flour_mixes/65/*.csv with label 0.65...
Processing ../glucose_flour_mixes/75/*.csv with label 0.75...
Processing ../glucose_flour_mixes/100/*.csv with label 1...

Wavenumber,4501.041,4504.898,4508.755,4512.612,4516.469,4520.326,4524.183,4528.040,4531.896,4535.754,...,9966.316,9970.173,9974.030,9977.887,9981.744,9985.601,9989.458,9993.314,9997.172,10001.030
0.0,0.368909,0.371250,0.365693,0.365159,0.360829,0.357576,0.355040,0.356554,0.354889,0.347379,...,0.184542,0.178153,0.177718,0.180572,0.173209,0.168235,0.171978,0.176712,0.172280,0.168966
0.0,0.174039,0.171243,0.155967,0.157244,0.160958,0.160517,0.163248,0.159695,0.159699,0.164543,...,0.148533,0.146436,0.142626,0.145708,0.151303,0.145216,0.132038,0.135004,0.136618,0.140038
0.0,0.136935,0.121657,0.128571,0.139961,0.128281,0.116669,0.125559,0.130501,0.128288,0.118640,...,0.061725,0.052813,0.050689,0.058184,0.062055,0.062467,0.065904,0.058885,0.050026,0.049251
0.0,0.406242,0.400763,0.402500,0.402956,0.405200,0.405639,0.394606,0.392809,0.388402,0.392009,...,0.068231,0.065292,0.067868,0.072777,0.068126,0.062028,0.065154,0.067731,0.067351,0.065652
0.0,0.362856,0.353994,0.346843,0.346984,0.347116,0.345381,0.343901,0.345708,0.334150,0.325251,...,0.142166,0.144459,0.144330,0.146200,0.151574,0.146458,0.141956,0.135055,0.132481,0.141057
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1.0,0.555258,0.556772,0.560092,0.556223,0.554091,0.554223,0.552431,0.560476,0.564071,0.570377,...,0.062581,0.061989,0.061168,0.060477,0.058960,0.063098,0.066309,0.062699,0.063096,0.061129
1.0,0.586003,0.593413,0.589558,0.598289,0.603600,0.606577,0.610223,0.606317,0.603439,0.606896,...,0.123145,0.124818,0.124524,0.126314,0.127380,0.129594,0.127124,0.126583,0.124586,0.125121
1.0,0.579945,0.592876,0.584950,0.580428,0.582088,0.575230,0.575615,0.583541,0.583483,0.592932,...,0.080313,0.077472,0.077117,0.078712,0.079774,0.082540,0.079884,0.077831,0.076295,0.074526
1.0,0.570594,0.573988,0.576377,0.572245,0.578236,0.583994,0.586108,0.586958,0.589191,0.591778,...,0.045519,0.042929,0.042077,0.044491,0.044328,0.043269,0.042787,0.042323,0.040255,0.040373
1.0,0.560474,0.554475,0.554789,0.558621,0.564401,0.570781,0.578055,0.568319,0.572939,0.576329,...,0.071323,0.067944,0.067224,0.065638,0.066325,0.070320,0.072691,0.070655,0.065343,0.063607

In [19]:
mean_data= pd.DataFrame(columns=data.columns)
for ind in set(data.index.to_list()):
    mean_data.loc[ind] = data.loc[ind].mean()

mean_data.to_csv("mean_flour_sugar_data.csv", index=True)

In [20]:
data = processing_pipeline(foods_fps, food_labels)
cols_to_drop = [col for col in data.columns if col <= 4500]
data = data.drop(columns=cols_to_drop)

data.to_csv("processed_foods_data.csv", index=True)
data

Processing ../foods/buttermilk_biscuit/*.csv with label buttermilk_biscuit...
Processing ../foods/inst_potatoes/*.csv with label inst_potatoes...
Processing ../foods/mixed_gravy/*.csv with label mixed_gravy...
Processing ../foods/nonfat_milk/*.csv with label nonfat_milk...
Processing ../foods/parmesan/*.csv with label parmesan...
Processing ../foods/parmesan_romano/*.csv with label parmesan_romano...
Processing ../foods/protein_pancake/*.csv with label protein_pancake...
Processing ../foods/tapioca/*.csv with label tapioca...

Wavenumber,4501.041,4504.898,4508.755,4512.612,4516.469,4520.326,4524.183,4528.040,4531.896,4535.754,...,9966.316,9970.173,9974.030,9977.887,9981.744,9985.601,9989.458,9993.314,9997.172,10001.030
buttermilk_biscuit,0.122664,0.119158,0.118186,0.120337,0.116341,0.121818,0.118069,0.118523,0.117388,0.117533,...,0.129149,0.123983,0.127351,0.134723,0.134399,0.124427,0.122702,0.125254,0.125208,0.131721
buttermilk_biscuit,0.154507,0.159807,0.159816,0.154425,0.143698,0.143324,0.142306,0.142803,0.148112,0.153268,...,0.148150,0.155304,0.155804,0.153847,0.154194,0.154129,0.152694,0.151190,0.152332,0.154823
buttermilk_biscuit,0.094460,0.104606,0.103955,0.090875,0.081105,0.083055,0.087677,0.089758,0.092323,0.090808,...,0.088762,0.095695,0.096416,0.094081,0.097831,0.098508,0.094591,0.095812,0.105010,0.099529
buttermilk_biscuit,0.172335,0.163363,0.154461,0.156848,0.164239,0.158716,0.156849,0.148939,0.162078,0.156832,...,0.161242,0.164884,0.165316,0.169488,0.168322,0.160556,0.158540,0.163411,0.165075,0.167231
buttermilk_biscuit,0.074529,0.079687,0.067179,0.057828,0.058841,0.067121,0.063869,0.075982,0.080948,0.069836,...,0.082871,0.099798,0.102654,0.102634,0.097374,0.102575,0.098238,0.090184,0.087354,0.087982
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
tapioca,0.736911,0.758390,0.772296,0.762103,0.751066,0.741194,0.729086,0.739743,0.736907,0.738242,...,0.041507,0.044871,0.048024,0.035699,0.044883,0.051959,0.067735,0.043422,0.023820,0.034843
tapioca,0.391639,0.390784,0.381159,0.378581,0.382307,0.381294,0.372819,0.372148,0.372172,0.378100,...,0.027148,0.037206,0.027121,0.022108,0.018667,0.022775,0.021592,0.018780,0.007594,0.019250
tapioca,0.450305,0.456324,0.446130,0.442380,0.441973,0.441261,0.430501,0.432847,0.437812,0.438709,...,0.022731,0.024733,0.031141,0.031272,0.027171,0.027428,0.033350,0.028102,0.021829,0.025048
tapioca,0.418569,0.427700,0.432843,0.426549,0.412199,0.404726,0.402743,0.405451,0.410520,0.410920,...,0.088886,0.095433,0.087756,0.078706,0.081031,0.085321,0.095764,0.088299,0.080859,0.086463
tapioca,0.656595,0.661773,0.666467,0.658399,0.653950,0.651871,0.645119,0.650385,0.656600,0.653535,...,0.029435,0.034931,0.034478,0.025316,0.026344,0.032874,0.027515,0.021246,0.013271,0.021955

In [21]:
mean_data= pd.DataFrame(columns=data.columns)
for ind in set(data.index.to_list()):
    mean_data.loc[ind] = data.loc[ind].mean()

mean_data.to_csv("mean_foods_data.csv", index=True)